# Generated by codegen compiler — DO NOT EDIT.
from manim import *


class Scene_Good_Test(Scene):
    def construct(self):
        # Simple, safe scene for testing
        title = Text("Good Scene Test", font=BODY_FONT).scale(0.9).to_edge(UP)
        self.play(Write(title))
        self.wait(0.5)

        eq = MathTex(r"y = x^2").scale(0.95)
        self.play(Write(eq))
        self.wait(0.5)

        self.wait(1.0)
